### PR TITLE
[fixed] Focus trap when reentering document (#742)

### LINKED ISSUE #742: Modal doesn't trap focus when re-entering document
### Summary:
react-modal doesn't trap focus when re-entering a document that contains an open modal.

### Steps to reproduce:

 1. Open a react-modal modal
 2. Move focus outside the document, for example by clicking the mouse in your browser's address bar or pressing ctrl+l
 3. Hit tab key a number of times until focus moves back into the document

### Expected behavior:
Focus is trapped inside the still-open modal when focus moves back into the document.

### Actual behavior:
Focus moves through the document behind the modal.

### Link to example of issue:
https://mgwy6v6e.codesandbox.io/

### Additional notes:
Compare this behaviour to https://davidtheclark.github.io/react-aria-modal/demo/ which doesn't have this issue.

### PR DESCRIPTION
**Pull request by holloway**
Fixes #742

Changes proposed:
- Ensure modal focus trap when reentering document. This restores modal focus when navigating into the page by keyboard. See discussion on #742 and #787

Upgrade Path (for changed or removed APIs):
- N/A

Acceptance Checklist:
- [x] The commit message follows the guidelines in `CONTRIBUTING.md`.
- ~[ ] Documentation (README.md) and examples have been updated as needed.~ *N/A I think*
- [ ] If this is a code change, a spec testing the functionality has been added.
- ~[ ] If the commit message has [changed] or [removed], there is an upgrade path above.~ *N/A I think*

### CODE REVIEW

**Comment by diasbruno** [comment]
Legit. @holloway Have you found what broke the tests?

**Comment by diasbruno** [comment]
@holloway Ping me if you need anything...not sure if I'm receiving the notifications from this repo or if I'm skipping without looking... :)

**Comment by holloway** [comment]
@diasbruno Yeah the test bug was caused by making those trap elements in `componentDidMount` rather than the constructor (or, presumably, willMount).

So that's passing now.

File: src/components/ModalPortal.js [hunk 1]
```diff
@@ -71,6 +71,15 @@ export default class ModalPortal extends Component {
...
     this.moveFromContentToOverlay = null;
+
+    // Body focus trap see Issue #742
+    this.bodyFocusTrapBefore = document.createElement("div");
+    this.bodyFocusTrapBefore.style.position = "absolute";
+    this.bodyFocusTrapBefore.style.opacity = "0";
+    this.bodyFocusTrapBefore.setAttribute("tabindex", "0");
+    this.bodyFocusTrapAfter = this.bodyFocusTrapBefore.cloneNode();
+    this.bodyFocusTrapBefore.addEventListener("focus", this.focusContent);
+    this.bodyFocusTrapAfter.addEventListener("focus", this.focusContent);
```
Comment (diasbruno) [inline src/components/ModalPortal.js]: This will create the trap elements for each modal created. 

Perhaps you can move this code to a new file and create these elements
in a singleton fashion.

Another question, though, is what would happen if there are nested modals opened?

Comment (diasbruno) [reply src/components/ModalPortal.js]: Maybe we need to track the lastest modal open (?)


NOTES: 
Probably we need to rewrite the way we manage nested modals.

Comment (holloway) [reply src/components/ModalPortal.js]: @diasbruno Yeah nested modals was why I was thinking it might be easier to just make a set of these per-modal. They 'wrap' the `<body>` nodes, and each subsequent modal adds another wrapping layer that's associated with only a single modal so giving focus via `this.bodyFocusTrapBefore.addEventListener("focus", this.focusContent);` is easy.

Happy to change it to a singleton approach though (that would make fewer `<div/>`s at the expense of a bit more complexity)... you mentioned a new file so I guess in that file I'd have a array of ModalPortal instances... pushing new ones on in `beforeOpen` and popping off in `afterClose`, and calling `this.focusContent` on the top modal when these trap elements were focused. Is that what you thinking?

Comment (diasbruno) [reply src/components/ModalPortal.js]: > I'd have a array of ModalPortal instances... pushing new ones on in beforeOpen and popping off in afterClose, and calling this.focusContent on the top modal when these trap elements were focused.

It seems the right way to go.

Comment (holloway) [reply src/components/ModalPortal.js]: @diasbruno is this what you were thinking, or is this too generic?

File: src/helpers/bodyTrap.js [hunk 2]
```diff
@@ -0,0 +1,48 @@
+import portalOpenInstances from "./portalOpenInstances";
+// Body focus trap see Issue #742
+
+let before, after, instances;
```
Comment (diasbruno) [inline src/helpers/bodyTrap.js]: Ýou can initialize `instances` with an empty array.

File: src/helpers/bodyTrap.js [hunk 3]
```diff
@@ -0,0 +1,48 @@
...
+
+function focusContent() {
+  if (!instances || instances.length === 0) {
+    // eslint-disable-next-line no-console
+    console.warn(`React-Modal: Open instances > 0 expected`);
+    return;
+  }
+  instances[instances.length - 1].focusContent();
```
Comment (diasbruno) [inline src/helpers/bodyTrap.js]: Maybe we can let this be no-op if there are no modals opened, or, maybe warn only in develoment mode. What do you think? 
 
```js
if (instances.lenght > 0) {
  instances[instances.length - 1].focusContent();
}
```

File: src/helpers/portalOpenInstances.js [hunk 4]
```diff
@@ -0,0 +1,51 @@
+// Tracks portals that are open and emits events to subscribers
```
Comment (diasbruno) [inline src/helpers/portalOpenInstances.js]: This looks really great. :+1:

File: src/components/ModalPortal.js (hunk 1 above)
Comment (diasbruno) [reply src/components/ModalPortal.js]: It's great.

File: src/helpers/portalOpenInstances.js (hunk 4 above)
Comment (holloway) [reply src/helpers/portalOpenInstances.js]: Thanks :smile:

File: src/helpers/bodyTrap.js (hunk 3 above)
Comment (holloway) [reply src/helpers/bodyTrap.js]: @diasbruno I agree, and as per the pattern in ModalPortal.js I've made all consoles only print in dev mode.

**Comment by diasbruno** [comment]
Thanks, @holloway. I merged your PR and will run a few tests on it. 
Don't let me forget to make a release. :)

**Comment by diasbruno** [comment]
@holloway When I'm move the focus back to the page view - testing on firefox -, I'm seen that I need "a extra tab" because `<html>` is getting the focus. Is this the correct behavior or a difference between browsers?

**Comment by holloway** [comment]
@diasbruno hmm... I can't reproduce that behaviour in Firefox v71 (Linux), and I haven't heard of Firefox overriding JS-controlled focus in that way. What are the exact reproduction steps? For me, in Firefox and in Chrome, it restores focus to the button that it opened from. This is a change in behaviour compared to this ReactCommunity Codepen examples? 

fyi I have tested focus management by running this to log the current element every second,

```
setInterval(function(){ console.log(document.activeElement); }, 1000);
```

And then interacting with the page to see how focus is moved around, and that part (when the page gets focus back) seems to behave as it was before this PR.

**Comment by diasbruno** [comment]
That look correct. Maybe when I click on the browsers console and type `document.activeElement`.

Steps
- Open modal
- Click on the browser's address
- Tab until it reaches the page view
- Go to browser's console and type `document.activeElement` (maybe this is why I'm getting the `<html>`)

**Comment by diasbruno** [comment]
Firefox 71 here.

**Comment by holloway** [comment]
Ah then yes that might move focus to `<html>`. The trap elements are in `<body>` so if the focus is on `<html>`, before the trap, then they haven't walked into the focus trap yet.

There's a legitimate question about whether focusing `<html>` _should_ move focus to the modal. I'm not sure of the answer to that, but I'll ask around with some accessibility experts that I know. If so, that would need a different approach than these trap elements, however in my testing it's basically harmless to allow `<html>` to be focused as the other content under the modal is still bypassed.

I guess the idea of using a `setInterval` was to poll the activeElement without needing to interact with the console which might change the activeElement and trigger a window `blur` event and react-modal changes (ie, I see focusManager.js responds to window blur).

**Comment by diasbruno** [comment]
LGTM. When we get more info about this, we can do something about this.

**Comment by holloway** [comment]
@diasbruno fyi I'm told that the extra tab in Firefox is expected behaviour that we wouldn't want to interfere with when a modal is open. FF users are in the habit of hitting tab twice, so this PRs' approach is still appropriate.

(@jasonkiss)

**Comment by holloway** [comment]
@diasbruno 

> Don't let me forget to make a release. :)

bump! :smile:

**Comment by diasbruno** [comment]
:man_facepalming:

Thanks, @holloway.
I'll make a release today.

**Comment by diasbruno** [comment]
Release `3.11.2`.

**Comment by holloway** [comment]
No probs, thanks @diasbruno !
