### PR TITLE
[fixed] stop propagating ESC key event.

### LINKED ISSUE #583: onRequestClose closes all modals when using them recursively.
### Summary:
When using nested react-modals, closing with escape key closes all modals instead of the last one open.
### Steps to reproduce:
 1. click open modal button
 2. inside Modal1, click open modal 2 button
 3. When modal 2 is open click escape key for close it.

### Expected behavior:
Only modal 2 is closed and modal 1 stays open.
### Link to example of issue:
https://codesandbox.io/s/w70xm5y1y7

### additional notes
I suppose this is related to this issue, when bubbling events with Modals it gets to the parent component. This behaviour depending on the situation is quite problematic. I think it didn't happened with old version before react 16 CreatePortal but now it does. Gonna try to create another codesandbox to confirm it.

### PR DESCRIPTION
**Pull request by diasbruno**
Fixes #583.

Changes proposed:
- Stop event propagation when on `handleKeyDown`. This is now required when nesting modals.

Upgrade Path (for changed or removed APIs):
- None

Acceptance Checklist:
- [x] All commits have been squashed to one.
- [x] The commit message follows the guidelines in `CONTRIBUTING.md`.
- [x] Documentation (README.md) and examples have been updated as needed.
- [x] If this is a code change, a spec testing the functionality has been added.
- [x] If the commit message has [changed] or [removed], there is an upgrade path above.

### CODE REVIEW

File: src/components/ModalPortal.js [hunk 1]
```diff
@@ -207,7 +207,7 @@ export default class ModalPortal extends Component {
     }
 
     if (this.props.shouldCloseOnEsc && event.keyCode === ESC_KEY) {
-      event.preventDefault();
```
Comment (Ne3l) [inline src/components/ModalPortal.js]: Does Remove prevenDefault break something? Why was there before?

Comment (diasbruno) [reply src/components/ModalPortal.js]: There is no need to `preventDefault` in this case, but instead to let only modal that receives this event to process it.

**Comment by Ne3l** [comment]
@diasbruno in #583 do you mention a test but isn't any test in this PR, it is already commited?

**Comment by diasbruno** [comment]
@Ne3l thanks. I've forgot to include the tests.

**Comment by diasbruno** [comment]
Added the missing test.

**Comment by diasbruno** [comment]
Thank you so much for helping.

**Comment by diasbruno** [comment]
Released `v3.1.9`.

**Comment by diasbruno** [comment]
Rereleased as `v3.1.10`. 
Published `3.1.9` was not released from `master` branch.
