### PR TITLE
[fixed] check if element exists before focusing in scopeTab helper

### LINKED ISSUE #687: Desktop Safari - Error in scopeTab.js
If focus is set to an element that isn't focusable, when the user tabs the variable x in scopeTab.js will be set to -1, then when tabbable[x].focus() is called an error will occur.

### PR DESCRIPTION
**Pull request by DarudeGarystorm**
Fixes #687

Changes proposed:
- check if element is undefined before focusing it

Acceptance Checklist:
- [x] The commit message follows the guidelines in `CONTRIBUTING.md`.
- [x] Documentation (README.md) and examples have been updated as needed.
- [ ] If this is a code change, a spec testing the functionality has been added.
- [x] If the commit message has [changed] or [removed], there is an upgrade path above.

### CODE REVIEW

File: src/helpers/scopeTab.js [hunk 1]
```diff
@@ -62,6 +62,10 @@ export default function scopeTab(node, event) {
     x += shiftKey ? -1 : 1;
   }
 
+  // If the tabbable element does not exist,
+  // let the browser control the focus
+  if (typeof tabbable[x] === "undefined") return;
```
Comment (diasbruno) [inline src/helpers/scopeTab.js]: Maybe, we actually need to focus the first element in this case, otherwise I suspect it can miss radios inputs.

Comment (DarudeGarystorm) [reply src/helpers/scopeTab.js]: Updated to focus head/tail based on shiftKey

Comment (diasbruno) [reply src/helpers/scopeTab.js]: Good catch!

**Comment by diasbruno** [comment]
Thanks you, @DarudeGarystorm!
