### PR TITLE
[fixed] Tab focus escapes modal on shift + tab after opening

### LINKED ISSUE #607: Tab focus escapes modal on shift + tab after opening
### Steps to reproduce:

 1. Open modal
 2. Hit `shift` + `tab` (before doing anything else)
 3. You'll see that the tab focus will move outside the modal.

### Expected behavior:
Tab focus is _always_ trapped inside the modal when it is open.

### Link to example of issue:
This can be reproduced in all the examples in this repo.

### PR DESCRIPTION
**Pull request by jasonblanchard**
Fixes #607.

Changes proposed:

Focusing the last tabbable element on `shift` + `tab` if the tab focus is on the modal content by checking if the shift key is active in `scopeTab` when tabbing off the modal content. Because the modal content has `tabindex="-1"`, this _should_ only happen after focus is programmatically given to the modal content on open.

Acceptance Checklist:
- [x] All commits have been squashed to one.
- [x] The commit message follows the guidelines in `CONTRIBUTING.md`.
- [x] Documentation (README.md) and examples have been updated as needed.
- [x] If this is a code change, a spec testing the functionality has been added.
- [x] If the commit message has [changed] or [removed], there is an upgrade path above.

### CODE REVIEW

File: src/helpers/scopeTab.js [hunk 1]
```diff
@@ -13,9 +13,11 @@ export default function scopeTab(node, event) {
   const head = tabbable[0];
   const tail = tabbable[tabbable.length - 1];
 
-  // proceed with default browser behavior
+  // proceed with default browser behavior on tab.
+  // Focus on last element on shift + tab.
   if (node === document.activeElement) {
-    return;
+    if (!shiftKey) return;
+    target = tail;
```
Comment (diasbruno) [inline src/helpers/scopeTab.js]: I think we should prepend the `node` to the list of tabbable.

`const tabbable = [node].concat(findTabbable(node));`

This way the node will always be the head.

`if (!tabbable.length) {` => `if (tabbable.length == 1) {` (above).

Comment (jasonblanchard) [reply src/helpers/scopeTab.js]: Would that break the concept of what `tabbable` means, though? In tabbable.js, it looks like it's looking for things that are naturally tab focusable which would [exclude the modal content `node` that has `tabindex="-1"`](https://github.com/reactjs/react-modal/blob/master/src/helpers/tabbable.js#L50).

I'm open to making that change, though. I'm not as familiar with the history of tabbable.js, here.

Comment (diasbruno) [reply src/helpers/scopeTab.js]: I think the question is (I'm also not sure about this) if it should cycle only on the children of the content or if the content should be allowed to gain the focus back.

If content should be focusable, the `tabIndex="-1"` can be removed (since it will be the first to receive the focus).

Comment (diasbruno) [reply src/helpers/scopeTab.js]: Thanks for the clarification.

**Comment by diasbruno** [comment]
Thanks for having a look on this.

**Comment by diasbruno** [comment]
Released `v3.1.13`.
